Repository quinoacomputing/quinoa, pull requests merged in 2021-11, with the labels that each got.

#527 Update some doc pages
  doc/pages/inciter.dox
  doc/pages/licenses.dox
  doc/pages/mainpage.dox
  doc/pages/meshconv.dox
Labels: doc

#528 static cast for shockmarker assignment
  src/Inciter/DG.cpp
Labels: bug

#529 remove factory policy output and unique code
  src/Base/Has.hpp
  src/Base/Print.hpp
  src/Control/Inciter/Options/AMRInitial.hpp
  src/Control/Inciter/Options/Physics.hpp
  src/Control/Inciter/Options/Problem.hpp
  src/Control/Keyword.hpp
  src/Control/Keywords.hpp
  src/Control/Walker/Options/CoeffPolicy.hpp
  src/Control/Walker/Options/InitPolicy.hpp
  src/Inciter/Transporter.cpp
  src/Main/InciterPrint.cpp
  src/Main/InciterPrint.hpp
  src/Main/WalkerPrint.hpp
  src/Walker/Distributor.cpp
  tests/unit/Base/TestHas.cpp
Labels: parser
